server:
  port: 8080 # trocar por property de ambiente

spring:
  application:
    name: acompanhamentoservice

  datasource:
    url: jdbc:postgresql://${DB_HOST_ACOMPANHAMENTO:localhost}:${DB_PORT_ACOMPANHAMENTO:5432}/${DB_NAME_ACOMPANHAMENTO:acompanhamento-service}
    username: ${DB_USER_ACOMPANHAMENTO:postgres}
    password: ${DB_PASSWORD_ACOMPANHAMENTO:senha_padrao}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    url: /acompanhamentoservice.yaml